apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Release.Name }}-{{ .Release.Name }}.apps.open-kvm1.localhost.com
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: http